name: mbie

base_params:
  num_states: ${environment.params.num_states}
  num_actions: ${environment.params.num_actions}
  threshold: 0.01
  epsilon_r_coeff: 0.3
  epsilon_t_coeff: 0.0
  exploration_coeff: 0.4
  r_max: 10_000
  discount: 0.95
  m: null
  use_exploration_bonus: false
  seed: null

RiverSwim:
  num_states: ${environment.params.num_states}
  num_actions: ${environment.params.num_actions}
  threshold: 0.01
  epsilon_r_coeff: 0.3
  epsilon_t_coeff: 0.0
  exploration_coeff: 0.0
  r_max: 10_000
  discount: 0.95
  m: 16
  use_exploration_bonus: false
  seed: null

SixArms:
  num_states: ${environment.params.num_states}
  num_actions: ${environment.params.num_actions}
  threshold: 0.01
  epsilon_r_coeff: 0.3
  epsilon_t_coeff: 0.08
  exploration_coeff: 0.0
  r_max: 6_000
  discount: 0.95
  m: 16
  use_exploration_bonus: false
  seed: null