name: rmax

base_params:
  num_states: ${environment.params.num_states}
  num_actions: ${environment.params.num_actions}
  threshold: 0.01
  r_max: 10_000
  discount: 0.95
  m: 16
  seed: null

RiverSwim:
  num_states: ${environment.params.num_states}
  num_actions: ${environment.params.num_actions}
  threshold: 0.01
  r_max: 10_000
  discount: 0.95
  m: 16
  seed: null

SixArms:
  num_states: ${environment.params.num_states}
  num_actions: ${environment.params.num_actions}
  threshold: 0.01
  r_max: 6_000
  discount: 0.95
  m: 6
  seed: null

